sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
  - secure: "bxEVve0is1j1V++hRco41ERkc9Dc9Sdh9RHMgXXz3iNuLe5i0MQWXx/Z5/ZRWMtqjOm9ho4RiK7U0b7cwRnN/TeegeNHpp2eQ0jjmUxOFklvqAcf9sunHgYw3yPyAKj3xYC63VQfKyXNrN3t4WpX+e0CLmS93Z3X/l/SYHuhz4mwN9yEvxBxyj8R00ykyhlZ2l8SQ9+1UG/QgIVDUDDtii7b4vUn2fzQPnMI45Xu1Lf1HMMmpgrMHgrmGB3KkE/PKdvNx1AXlwkMEV6C04W0l97AN2IWlZ5+raV57QgSfmD32rljL2JV2p1ifCBZgucerDm5Su0feN+tZKKqUjX6DWc6eNxdoSnWKLpE/ipvmMR5puzyVaDUIliwtAboaFIAS0RiF6QksgQUKqglWnKQq1adSWYcjY+vgRkAHoVd/aHFPHZfN3wpdq9VKsaOZ9sRa8FxP0FRQ1aNLtAn5cwojfUTFB9rkFHWIzCGuoiWrnf+Ftw0CNQw4gQK2xVc5nloqugSsB4bDz6EnH/wsgBt2dj8l9ps5CIoN8eb5JdaGi1ZuuiMApBiY63Th+L84jToIgqp8YZQftJM3hK3+vNlGBzHMNPTW5a8/TkWrmL137mvR/9oMIOb9s6r1A4p/pG6MzTqig+SwDV3LBd9/x7O7d/LNbwFGIC+IL2IBi02AZM="
  # Ex. travis encrypt -r org/repo SONATYPE_USER=your_sonatype_account
  - secure: "Q9CncPKCLUwfZRmgDOtS1XpLn/kweKoC8ifCJ+ptBBkv6+cOJgyOMD3hhDxlSGUyD82Mc6dISWSR1L5DHmuC6/Yz9aHNlNzY7XD9QSb6Y3QQi486IQ6HKo8x6LKiBT7QJNUCNRln7ed2X5dMDaFWBe0nhDs5R7ir9ygpR/yLSsk4alu5OJ9U2q4bpG9EdM2ybxcNjCacEWxFoVYAFeNeQZoI6E+huee6G1TGRIuRUpD/78yemQ9t2O0+W4ftl5yAKRP38Z2Hj0iRDbA6Js1NkiSve8dhCsCFWGuinTZAsoe7nMNwyZDb5Ein8MMFE30hIRstewOux2dVz2uly3B/VB6vOUzv3Xu3GNaADfxioDl396NMAwTF5k3NB4KSO472P5CpYSwIA8uIqw6r8fi7o7weLTOdsj4J1QKvmeSPiiaDGr7QHIgmyqekekZzs+LeArWF8bFgt9Kwymmw8bnN0P4/GD8gukEwuFi1FCjh5DOJyJTYhXrDbPZH+1IzqN9B6MvnXcni+kvbr3IEx7PVKhuGyvff28lBZadHu9C4PSo3vnhdHIRO3W1heXDg0CeUDor1kV6Q/V7uwUxRjg1a9YcMhrzghsyQKtKeiXwiXmugECan7sz8ccBza2YEjmd+gvSj2+60YybzDhxtQ1i+85Yv1k9uH3wtUDDeTf05V0M="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "nfyD0kTNR5UpZv3X6E+ZEUuD7MeGSyfFONFiZKapNRs3X057G1TqdPEabYhbztF2cJ+qkSGeVB/gXNE8iPnSLQ6xev49xn6CaK5lc1PlJxF3wxyjrsOt1/JAoZP2w3457KbQK0FHU7ZLyiNLQTTtBYHLE1wAymCStoGY4ZZa/ZWeGE5eKb/7kiUMGNlS6Nyw8Xlt3NlshfJXSinBr8DrfV1iQYT90a7MnA1nxFD9QOEEKmGAMY7yp3ArrcBo/E7BeM1zOXECWmqQnoIoX4wa9xN1Oifb6+Om4YOlu8hp26lVtMnQ7k5etXvRw0dRITqHeqjppQnc/vRyGu/Q5DK3rPfzYZnrauRMRknSsJQcj09Cg5C6et8RhPklOsG9Nsal6gleaeYcfDyW/MICUyLyLv27v5Y6zit01cPCCnMUiJmR0Lv/66YjvsxItZsMq1EoIXYpqu2zy9htgk3p6tWFrb1UmU3SdH7TpeaMvQXRrSsjkOfQbjtfv8Rg52hkfyfYPnuNpIb8a3OmCFe3WCQdLnWUJHBLuBIjOYnMP1YCCTC80sxs9R9I/fniSornaxyn2ScWbh7EzhCbiIwv3bP3r6xDQ8xhQZwrPdIOmQJXhVz9NQZL/5uNDdACq5Hsos1toIcffp6MwyvNtDKTbuGe3mYqwQQ3Vq2Eta3rOsGAq3g="
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "Ehpn1emRw4A4yqrm4LQeibAdmY454vUKSECcRwx9DRlPhmAAsmwapr1p29S398I2GmSi+vqUS1nKenwZmiJSTF1Q0BgN0jK8rz4Vwr3MBrDXNZ3D77qbtKphdhSnkoWZRY8P4CHVqnB8eRs/6uMR7yEMYfhS6YyGJcsDSo90ZJAStwj0V7fI2tMLtQHzZkR1sDHWpQkv6axm4iMZSHZSDQnshZ0gWrSabpvqI+6zCj5IW57ZbL5brDoj6MRRF7q07WhMpFxjRvF18M/UzDeZF3n7YYyR7VdhU7Ysuv0ECEk4f74x77LAALoWZz9x/fTGIyKHP41tD1DdYD0JJ4L5vjza17PkB0Ps4Q7QTXm/FWah/y1zqQSFkS+tSoQltyMBc09P2NcWsAznyCP5OtVrouQTYF7BhlpyFi3PGKXS+pygcMdcCb7KcF+QqAKypS9dZsYj+ZDYqBtVBUljSYdLlXToty7PtvMYNUbvKpUHfKBYS2/CyshE/n+pNySI0fkPojLQE6zRg8CoOKAfHf8H8W5QN/3vRMn5wWGKPe43aPTnP9hS8dwdxGWawr2V+NqpFmGv/sFpz8i+qADfGz090adeJ+i+IUDMHgqvhsYT3vg6yypmlWCflZkHodYXXOtQiNCOQKt1ZRrKNPwJooPO5kWAD9mGS8KhPl3jE4R9qTw="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx
  - secure: "g/ulmoeKwXKE+RXssCwqjpCsARiSYrX5Lj2arXytndH2Pi+rvd7ZTidjCXhboxdJHm7uJ6zjp1Kmso3W6b3nt9btIppys/f4vK6uUncj3oufLak0uV7PPpnCxAf+yp3+mUt727jaXde2/tznSt4q8K2nJmc6Xz/19TYF1rMnRKwHltuRYiyC/XDLWx15p3/SJIY91KC9HNQoyf+xKzyovP5j+3lwHuvhb0FwgiaaMXBAfB4k1+8+SiLyzCjqPK68Pejm/pIltaZ86pw/c9GdIIvAlt8ZCkvUu13qNZ7fHflNNINuogr/bePu+3cjbvl3Y1dLsuFYKMd5EiYTUYyHdoJLSLXGNtOK35P0ewuForvQUrPHSXwW+I+jli+YP0xMKydG49HbqM+mg73HYKT4IDyDUA+udI6YlFuV08XkQFwoVCuorr1SVOGJOPCIP83uR4Vc/vblefPb+IkSH34vfXgSF03ASvrQfcvf7xz6oKIiEdtRQFEdLCby79+IANnAteyyEjpgJtLNIJy6dhy/lKPlcQj42J6w4AP3iKelKov3pIiQCw42scqCbPUuNBYtUcKUB/cdAYSJ2apNNoEyeeoYb0xYUy0plSRcjHo9pgIpaCcxJ/GraJSirYHmsxIDDiCujQQEro/XUaQWotXwJ6Js3s/3CD18N7AMLMTkPFk="
